language: node_js
node_js:
- node
script:
- cd ./src && ./build.sh
deploy:
  provider: releases
  api_key:
    secure: Xq6eFqbnHDL7JwYS7J16oY4ntNpl6ekSxAWM+k6RDdQlScW7ekmy8KPGU1GKHdFMETd5e+TRtTQdh7PdPoZLOVK5lhZ9CWiNZoItnaTmBV7fBjhG/tDVPwahuk0bRECYEvAZxsEh9i3qAKxbGPIzhQhPFyigmbOYFT6Uwjmdv1UW6k5JHcL6VCePqD9EkOL+R5C82mDWV9eO1t1t6jDFaR0civRCU+y1SSCmIpVqDCGEhdG5vzcIyU/KuKzjgeQiNSsWqb6FKU5DknnERvaHJ+Waav4MUtYxO1hYfTS7ssiBpLce3kpHpXk5LvLJKT3QVgNk/LODq2KdejoQxW/yBJm9xaLTY+rSs+bHhnubYtqHG6wq+5tqu1Cj/8bFd4DPO5C2P4UXw3eZ3HSyjGQ5nnZAR7foaZoN4geVL9T/Ee7aVjd2/blYQFFqbjGw88MPV0lQNWGHO+rqeSGXRqVOGDgddh4gveQ3ktiJ4IB23Q9+expJxoIE9EBvkyBvUZ6UfQm6WCAyp5vCViAGjfcjClRAagE0IXxld0WgCFwJH3Z0Q7YrX+9WY8XZZtbhoAnVM/6AycK8HmjtR2twkrYEyniE/WG148etfLJFspSHJspMuBpzSv2GZ3s5MXO38yTGGg1KYHBNvrIzuzgAzbtHK7SQzKP/Yrld+8HvuRzE9Xk=
  file: src/restclient-aps.xpi
  skip_cleanup: true
  on:
    repo: mastacheata/RESTClient-APS
